name: Deploy to Production

on:
  pull_request:
    branches:
      - master
    paths:
      - 'force-app/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    timeout-minutes: 30
    env:
      ENVIRONMENT_NAME: Production
      SF_ORG_ALIAS: mockUp
      TEST_LEVEL: RunAllTestsInOrg

    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      # Cache Salesforce CLI
      - name: Cache Salesforce CLI
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: sf-cli-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: sf-cli-${{ runner.os }}-

      # Install Salesforce CLI
      - name: Install Salesforce CLI
        run: |
          npm install --global @salesforce/cli

      # Authenticate to Salesforce Org
      - name: Authenticate to Salesforce Org
        run: |
          echo ${{ secrets.SFDX_AUTH_URL }} > auth.txt
          sf org login sfdx-url --sfdx-url-file auth.txt --alias $SF_ORG_ALIAS --set-default
          rm -f auth.txt

      # Run Code Analysis
      - name: Run Code Analysis
        run: |
          sf scanner run --target 'force-app/**' --category "Best Practices,Performance"

      # Deploy to Production with Rollback
      - name: Deploy to ${{ env.ENVIRONMENT_NAME }}
        run: |
          sf project deploy start \
            --target-org $SF_ORG_ALIAS \
            --test-level $TEST_LEVEL \
            --verbose \
            --rollback-on-error \
            --parallel | tee deploy.log

      # Upload Deployment Logs on Failure
      - name: Upload Deployment Logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: deployment-logs
          path: deploy.log

      # Deployment Success Message
      - name: Deployment Success
        if: success()
        run: echo "✅ Deployment to ${{ env.ENVIRONMENT_NAME }} was successful!"

      # Deployment Failure Message
      - name: Deployment Failed
        if: failure()
        run: echo "❌ Deployment to ${{ env.ENVIRONMENT_NAME }} failed. Check the logs for details."

      # Logout from SF
      - name: Logout from Salesforce Org
        if: always()
        run: sf org logout --target-org $SF_ORG_ALIAS --no-prompt